// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xapply.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XApply_CfgInitialize(XApply *InstancePtr, XApply_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Fir_io_BaseAddress = ConfigPtr->Fir_io_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XApply_Start(XApply *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_AP_CTRL) & 0x80;
    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XApply_IsDone(XApply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XApply_IsIdle(XApply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XApply_IsReady(XApply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XApply_EnableAutoRestart(XApply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_AP_CTRL, 0x80);
}

void XApply_DisableAutoRestart(XApply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_AP_CTRL, 0);
}

u32 XApply_Get_Y(XApply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_Y_DATA);
    return Data;
}

u32 XApply_Get_Y_vld(XApply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_Y_CTRL);
    return Data & 0x1;
}

void XApply_Set_x(XApply *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_X_DATA, Data);
}

u32 XApply_Get_x(XApply *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_X_DATA);
    return Data;
}

void XApply_InterruptGlobalEnable(XApply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_GIE, 1);
}

void XApply_InterruptGlobalDisable(XApply *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_GIE, 0);
}

void XApply_InterruptEnable(XApply *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_IER);
    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_IER, Register | Mask);
}

void XApply_InterruptDisable(XApply *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_IER);
    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_IER, Register & (~Mask));
}

void XApply_InterruptClear(XApply *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XApply_WriteReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_ISR, Mask);
}

u32 XApply_InterruptGetEnabled(XApply *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_IER);
}

u32 XApply_InterruptGetStatus(XApply *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XApply_ReadReg(InstancePtr->Fir_io_BaseAddress, XAPPLY_FIR_IO_ADDR_ISR);
}

