# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.srcs/sources_1/bd/system/ip/system_apply_1_0/system_apply_1_0.xci
# IP: The module: 'system_apply_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.srcs/sources_1/bd/system/ip/system_apply_1_0/constraints/apply_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_apply_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.srcs/sources_1/bd/system/ip/system_apply_1_0/system_apply_1_0.xci
# IP: The module: 'system_apply_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.srcs/sources_1/bd/system/ip/system_apply_1_0/constraints/apply_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_apply_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
