# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2.xci
# IP: The module: 'design_4_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2.xci
# IP: The module: 'design_4_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/hardwaremodel/project/project.srcs/sources_1/bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
