set_property PACKAGE_PIN M14 [get_ports leds[0]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[0]]
set_property PACKAGE_PIN M15 [get_ports leds[1]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[1]]
set_property PACKAGE_PIN G14 [get_ports leds[2]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[2]]
set_property PACKAGE_PIN D18 [get_ports leds[3]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[3]]

set_property PACKAGE_PIN G15 [get_ports switches[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[0]]
set_property PACKAGE_PIN P15 [get_ports switches[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[1]]
set_property PACKAGE_PIN W13 [get_ports switches[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[2]]
set_property PACKAGE_PIN T16 [get_ports switches[3]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[3]]

#set_input_delay 0 -clock CLK  [all_inputs]
#set_output_delay 0 -clock CLK [all_outputs]