// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Advios_LedControl.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Advios_LedControl::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Advios_LedControl::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> Advios_LedControl::ap_ST_fsm_state2 = "10";
const sc_lv<4> Advios_LedControl::ap_const_lv4_0 = "0000";
const sc_lv<32> Advios_LedControl::ap_const_lv32_1 = "1";
const sc_lv<1> Advios_LedControl::ap_const_lv1_1 = "1";
const sc_lv<1> Advios_LedControl::ap_const_lv1_0 = "0";
const sc_lv<4> Advios_LedControl::ap_const_lv4_8 = "1000";
const sc_lv<4> Advios_LedControl::ap_const_lv4_1 = "1";
const bool Advios_LedControl::ap_const_boolean_1 = true;

Advios_LedControl::Advios_LedControl(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_outLeds);
    sensitive << ( v_V_1_fu_127_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_104_p2 );
    sensitive << ( tmp_3_fu_117_p2 );
    sensitive << ( r_V_fu_110_p2 );

    SC_METHOD(thread_outLeds_ap_vld);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_104_p2 );
    sensitive << ( tmp_3_fu_117_p2 );

    SC_METHOD(thread_r_V_fu_110_p2);
    sensitive << ( ctrl );
    sensitive << ( inSwitch );

    SC_METHOD(thread_tmp_3_fu_117_p2);
    sensitive << ( inSwitch );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_104_p2 );

    SC_METHOD(thread_tmp_fu_104_p2);
    sensitive << ( ctrl );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_v_V_1_fu_127_p2);
    sensitive << ( counter_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    counter_V = "0000";
    ap_CS_fsm = "10";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Advios_LedControl_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ctrl, "(port)ctrl");
    sc_trace(mVcdFile, inSwitch, "(port)inSwitch");
    sc_trace(mVcdFile, outLeds, "(port)outLeds");
    sc_trace(mVcdFile, outLeds_ap_vld, "(port)outLeds_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, counter_V, "counter_V");
    sc_trace(mVcdFile, v_V_1_fu_127_p2, "v_V_1_fu_127_p2");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_104_p2, "tmp_fu_104_p2");
    sc_trace(mVcdFile, tmp_3_fu_117_p2, "tmp_3_fu_117_p2");
    sc_trace(mVcdFile, r_V_fu_110_p2, "r_V_fu_110_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Advios_LedControl::~Advios_LedControl() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Advios_LedControl::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state2;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_104_p2.read(), ap_const_lv1_1))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_117_p2.read())) {
            counter_V = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(tmp_3_fu_117_p2.read(), ap_const_lv1_0)) {
            counter_V = v_V_1_fu_127_p2.read();
        }
    }
}

void Advios_LedControl::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Advios_LedControl::thread_outLeds() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if ((esl_seteq<1,1,1>(tmp_fu_104_p2.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_117_p2.read()))) {
            outLeds = ap_const_lv4_0;
        } else if ((esl_seteq<1,1,1>(tmp_fu_104_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(tmp_3_fu_117_p2.read(), ap_const_lv1_0))) {
            outLeds = v_V_1_fu_127_p2.read();
        } else if (esl_seteq<1,1,1>(tmp_fu_104_p2.read(), ap_const_lv1_0)) {
            outLeds = r_V_fu_110_p2.read();
        } else {
            outLeds = "XXXX";
        }
    } else {
        outLeds = "XXXX";
    }
}

void Advios_LedControl::thread_outLeds_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_fu_104_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(tmp_3_fu_117_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_fu_104_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_117_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_fu_104_p2.read(), ap_const_lv1_0)))) {
        outLeds_ap_vld = ap_const_logic_1;
    } else {
        outLeds_ap_vld = ap_const_logic_0;
    }
}

void Advios_LedControl::thread_r_V_fu_110_p2() {
    r_V_fu_110_p2 = (inSwitch.read() & ctrl.read());
}

void Advios_LedControl::thread_tmp_3_fu_117_p2() {
    tmp_3_fu_117_p2 = (!inSwitch.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(inSwitch.read() == ap_const_lv4_8);
}

void Advios_LedControl::thread_tmp_fu_104_p2() {
    tmp_fu_104_p2 = (!ctrl.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(ctrl.read() == ap_const_lv4_0);
}

void Advios_LedControl::thread_v_V_1_fu_127_p2() {
    v_V_1_fu_127_p2 = (!counter_V.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(counter_V.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Advios_LedControl::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

}

