// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Advios_HH_
#define _Advios_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Advios_LedControl.h"
#include "Advios_modulate_clock.h"

namespace ap_rtl {

struct Advios : public sc_module {
    // Port declarations 7
    sc_in_clk clk;
    sc_in_clk clk_sc_in;
    sc_out< sc_logic > clk_sc_out;
    sc_in< sc_logic > reset;
    sc_in< sc_lv<4> > ctrl;
    sc_in< sc_lv<4> > inSwitch;
    sc_out< sc_lv<4> > outLeds;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    Advios(sc_module_name name);
    SC_HAS_PROCESS(Advios);

    ~Advios();

    sc_trace_file* mVcdFile;

    Advios_LedControl* grp_Advios_LedControl_fu_76;
    Advios_modulate_clock* grp_Advios_modulate_clock_fu_96;
    sc_signal< sc_lv<1> > Advios_ssdm_threa_load_fu_114_p1;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_lv<4> > grp_Advios_LedControl_fu_76_outLeds;
    sc_signal< sc_logic > grp_Advios_LedControl_fu_76_outLeds_ap_vld;
    sc_signal< sc_logic > grp_Advios_modulate_clock_fu_96_clk_sc_out;
    sc_signal< sc_logic > grp_Advios_modulate_clock_fu_96_clk_sc_out_ap_vld;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_clk_sc_out();
    void thread_outLeds();
    void thread_Advios_ssdm_threa_load_fu_114_p1();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
};

}

using namespace ap_rtl;

#endif
