// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Advios_modulate_clock_HH_
#define _Advios_modulate_clock_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Advios_modulate_clock : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > clk_sc_in;
    sc_out< sc_logic > clk_sc_out;
    sc_out< sc_logic > clk_sc_out_ap_vld;


    // Module declarations
    Advios_modulate_clock(sc_module_name name);
    SC_HAS_PROCESS(Advios_modulate_clock);

    ~Advios_modulate_clock();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<26> > clock_counter_V_fu_86;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<26> > clock_counter_V_assi_fu_112_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_1_fu_118_p2;
    sc_signal< sc_lv<1> > v_fu_129_p0;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<26> ap_const_lv26_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<26> ap_const_lv26_1;
    static const sc_lv<26> ap_const_lv26_2FAF080;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_clk_sc_out();
    void thread_clk_sc_out_ap_vld();
    void thread_clock_counter_V_assi_fu_112_p2();
    void thread_tmp_1_fu_118_p2();
    void thread_v_fu_129_p0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
