// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Advios_LedControl.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Advios_LedControl::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Advios_LedControl::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Advios_LedControl::ap_ST_fsm_state2 = "10";
const sc_lv<3> Advios_LedControl::ap_ST_fsm_state3 = "100";
const sc_lv<1> Advios_LedControl::ap_const_lv1_0 = "0";
const sc_lv<4> Advios_LedControl::ap_const_lv4_0 = "0000";
const sc_lv<32> Advios_LedControl::ap_const_lv32_2 = "10";
const sc_lv<32> Advios_LedControl::ap_const_lv32_1 = "1";
const sc_lv<1> Advios_LedControl::ap_const_lv1_1 = "1";
const sc_lv<4> Advios_LedControl::ap_const_lv4_8 = "1000";
const sc_lv<4> Advios_LedControl::ap_const_lv4_1 = "1";
const bool Advios_LedControl::ap_const_boolean_1 = true;

Advios_LedControl::Advios_LedControl(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_54);
    sensitive << ( grp_read_fu_78_p2 );
    sensitive << ( last_clock_load_load_fu_104_p1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_condition_75);
    sensitive << ( grp_read_fu_78_p2 );
    sensitive << ( last_clock_load_load_fu_104_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_3_fu_108_p2 );

    SC_METHOD(thread_grp_read_fu_78_p2);
    sensitive << ( clk_second );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( last_clock_load_load_fu_104_p1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_last_clock_load_load_fu_104_p1);
    sensitive << ( last_clock );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_leds);
    sensitive << ( v_V_1_fu_131_p2 );
    sensitive << ( tmp_3_fu_108_p2 );
    sensitive << ( tmp_4_fu_121_p2 );
    sensitive << ( r_V_fu_114_p2 );
    sensitive << ( ap_condition_54 );

    SC_METHOD(thread_leds_ap_vld);
    sensitive << ( grp_read_fu_78_p2 );
    sensitive << ( last_clock_load_load_fu_104_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_3_fu_108_p2 );
    sensitive << ( tmp_4_fu_121_p2 );

    SC_METHOD(thread_r_V_fu_114_p2);
    sensitive << ( ctrl );
    sensitive << ( switches );

    SC_METHOD(thread_tmp_3_fu_108_p2);
    sensitive << ( ctrl );
    sensitive << ( grp_read_fu_78_p2 );
    sensitive << ( last_clock_load_load_fu_104_p1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_4_fu_121_p2);
    sensitive << ( switches );
    sensitive << ( grp_read_fu_78_p2 );
    sensitive << ( last_clock_load_load_fu_104_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_3_fu_108_p2 );

    SC_METHOD(thread_v_V_1_fu_131_p2);
    sensitive << ( counter_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    last_clock = "0";
    counter_V = "0000";
    ap_CS_fsm = "010";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Advios_LedControl_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, clk_second, "(port)clk_second");
    sc_trace(mVcdFile, ctrl, "(port)ctrl");
    sc_trace(mVcdFile, switches, "(port)switches");
    sc_trace(mVcdFile, leds, "(port)leds");
    sc_trace(mVcdFile, leds_ap_vld, "(port)leds_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, last_clock, "last_clock");
    sc_trace(mVcdFile, counter_V, "counter_V");
    sc_trace(mVcdFile, grp_read_fu_78_p2, "grp_read_fu_78_p2");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, last_clock_load_load_fu_104_p1, "last_clock_load_load_fu_104_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, v_V_1_fu_131_p2, "v_V_1_fu_131_p2");
    sc_trace(mVcdFile, tmp_3_fu_108_p2, "tmp_3_fu_108_p2");
    sc_trace(mVcdFile, tmp_4_fu_121_p2, "tmp_4_fu_121_p2");
    sc_trace(mVcdFile, r_V_fu_114_p2, "r_V_fu_114_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_75, "ap_condition_75");
    sc_trace(mVcdFile, ap_condition_54, "ap_condition_54");
#endif

    }
}

Advios_LedControl::~Advios_LedControl() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Advios_LedControl::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state2;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_75.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_121_p2.read())) {
            counter_V = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_121_p2.read())) {
            counter_V = v_V_1_fu_131_p2.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        last_clock =  (sc_lv<1>) (clk_second.read());
    }
}

void Advios_LedControl::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Advios_LedControl::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Advios_LedControl::thread_ap_condition_54() {
    ap_condition_54 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, last_clock_load_load_fu_104_p1.read()) && esl_seteq<1,1,1>(grp_read_fu_78_p2.read(), ap_const_lv1_1));
}

void Advios_LedControl::thread_ap_condition_75() {
    ap_condition_75 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, last_clock_load_load_fu_104_p1.read()) && esl_seteq<1,1,1>(grp_read_fu_78_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_108_p2.read()));
}

void Advios_LedControl::thread_grp_read_fu_78_p2() {
    grp_read_fu_78_p2 =  (sc_lv<1>) (clk_second.read());
}

void Advios_LedControl::thread_last_clock_load_load_fu_104_p1() {
    last_clock_load_load_fu_104_p1 = last_clock.read();
}

void Advios_LedControl::thread_leds() {
    if (esl_seteq<1,1,1>(ap_condition_54.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_108_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_121_p2.read()))) {
            leds = ap_const_lv4_0;
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_108_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_121_p2.read()))) {
            leds = v_V_1_fu_131_p2.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_108_p2.read())) {
            leds = r_V_fu_114_p2.read();
        } else {
            leds = "XXXX";
        }
    } else {
        leds = "XXXX";
    }
}

void Advios_LedControl::thread_leds_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, last_clock_load_load_fu_104_p1.read()) && 
          esl_seteq<1,1,1>(grp_read_fu_78_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_108_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_121_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, last_clock_load_load_fu_104_p1.read()) && 
          esl_seteq<1,1,1>(grp_read_fu_78_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_3_fu_108_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_121_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, last_clock_load_load_fu_104_p1.read()) && 
          esl_seteq<1,1,1>(grp_read_fu_78_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_108_p2.read())))) {
        leds_ap_vld = ap_const_logic_1;
    } else {
        leds_ap_vld = ap_const_logic_0;
    }
}

void Advios_LedControl::thread_r_V_fu_114_p2() {
    r_V_fu_114_p2 = (switches.read() & ctrl.read());
}

void Advios_LedControl::thread_tmp_3_fu_108_p2() {
    tmp_3_fu_108_p2 = (!ctrl.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(ctrl.read() == ap_const_lv4_0);
}

void Advios_LedControl::thread_tmp_4_fu_121_p2() {
    tmp_4_fu_121_p2 = (!switches.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(switches.read() == ap_const_lv4_8);
}

void Advios_LedControl::thread_v_V_1_fu_131_p2() {
    v_V_1_fu_131_p2 = (!counter_V.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(counter_V.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Advios_LedControl::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

