webtalk_init -webtalk_dir /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-01-04 22:53:30" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7mfnm25vg3125hvt5pc6suvcns" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808.001 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16,796 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1546627396000" -context "sdk\\\\bsp/1546627396000"
webtalk_add_data -client sdk -key hwid -value "1546622439000" -context "sdk\\\\bsp/1546627396000"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\bsp/1546627396000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1546627396000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1546627396000"
webtalk_add_data -client sdk -key uid -value "1546627658000" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key hwid -value "1546622439000" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key bspid -value "1546627396000" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key projSize -value "1218.12890625" -context "sdk\\\\application/1546627658000"
webtalk_add_data -client sdk -key uid -value "1546629093000" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key hwid -value "1546622439000" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key bspid -value "1546627396000" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1546629093000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1546638810819"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1546638810819"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1546638810819"
webtalk_add_data -client sdk -key DebugCount -value "70" -context "sdk\\\\bsp/1546638810819"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1546638810819"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1546638810819"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1546638810819"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1546638810819"
webtalk_transmit -clientid 1714493617 -regid "" -xml /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/olafur/Documents/Embedded_systems/-EmbeddedRealTimeSystems-/project/lab_based_hardware/audio/audio.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
