# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

set ::env(LD_LIBRARY_PATH) /opt/Xilinx/Vivado/2018.2/lnx64/tools/fpo_v7_0:$::env(LD_LIBRARY_PATH)

set ::env(LD_LIBRARY_PATH) /opt/Xilinx/Vivado/2018.2/lnx64/tools/opencv:$::env(LD_LIBRARY_PATH)
set ::env(LD_LIBRARY_PATH) /opt/Xilinx/Vivado/2018.2/lnx64/tools/fft_v9_1:$::env(LD_LIBRARY_PATH)
set ::env(LD_LIBRARY_PATH) /opt/Xilinx/Vivado/2018.2/lnx64/tools/fir_v7_0:$::env(LD_LIBRARY_PATH)
set ::env(LD_LIBRARY_PATH) /opt/Xilinx/Vivado/2018.2/lnx64/tools/dds_v6_0:$::env(LD_LIBRARY_PATH)
set ::env(LD_LIBRARY_PATH) /usr/lib/x86_64-linux-gnu:$::env(LD_LIBRARY_PATH)

source check_sim.tcl


# --> systemc simulation

::AP::printMsg INFO COSIM 11 COSIM_11_1002

cd ../systemc

# remove hdltvin&hdltvout in tv dir
file delete -force [file join "../tv" Advios.hdltvin.dat]
file delete -force [file join "../tv" Advios.hdltvout.dat]

set ::env(AP_WRITE_TV) "on"

file delete -force  "err.log"

if {![file exists cosim.sc.exe]} {
	::AP::printMsg ERR COSIM 321 COSIM_321_1003
	return -code error -errorcode $::errorCode
}

set ret [catch {eval exec ./cosim.sc.exe | tee temp1.log >&@ stdout} err]

if {$ret == 1} {
	::AP::printMsg ERR COSIM 344 COSIM_344_1004
	return -code error -errorcode $::errorCode
}

if {[file isfile Advios.hdltvin.dat]} {
	file copy -force Advios.hdltvin.dat [file join "../tv" Advios.hdltvin.dat]
}
if {[file isfile Advios.hdltvout.dat]} {
	file copy -force Advios.hdltvout.dat [file join "../tv" Advios.hdltvout.dat]
}

sc_sim_check $ret $err "temp1.log"

# --> vhdl simulation

::AP::printMsg INFO COSIM 322 COSIM_322_1006

::AP::printMsg INFO COSIM 15 COSIM_15_1011

cd ../vhdl

if {![file exists [file join "../tv" Advios.hdltvin.dat]]} {
	::AP::printMsg ERR COSIM 332 COSIM_332_1014 $::AESL_AUTOSIM::gConstFileHdlTvIn
	return -code error -errorcode $::errorCode
}

file copy -force [file join "../tv" Advios.hdltvin.dat] Advios.hdltvin.dat

file copy -force [file join "../tv" Advios.hdltvout.dat] Advios.hdltvout.dat

file delete -force ".exit.err"
file delete -force ".aesl_error"
file delete -force "err.log"

if {[file isfile run_xsim.sh]} {
	set ret [catch {eval exec "sh ./run_xsim.sh | tee temp2.log" >&@ stdout} err]
}
