// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Advios_HH_
#define _Advios_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Advios_LedControl.h"
#include "Advios_modulate_clock.h"

namespace ap_rtl {

struct Advios : public sc_module {
    // Port declarations 5
    sc_in_clk clk;
    sc_in< sc_logic > reset;
    sc_in< sc_lv<4> > ctrl;
    sc_in< sc_lv<4> > switches;
    sc_out< sc_lv<4> > leds;


    // Module declarations
    Advios(sc_module_name name);
    SC_HAS_PROCESS(Advios);

    ~Advios();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Advios_LedControl* grp_Advios_LedControl_fu_70;
    Advios_modulate_clock* grp_Advios_modulate_clock_fu_90;
    sc_signal< sc_lv<1> > Advios_ssdm_threa_load_fu_108_p1;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > grp_Advios_LedControl_fu_70_clk_second;
    sc_signal< sc_lv<4> > grp_Advios_LedControl_fu_70_leds;
    sc_signal< sc_logic > grp_Advios_LedControl_fu_70_leds_ap_vld;
    sc_signal< sc_logic > grp_Advios_modulate_clock_fu_90_clk_second_i;
    sc_signal< sc_logic > grp_Advios_modulate_clock_fu_90_clk_second_o;
    sc_signal< sc_logic > grp_Advios_modulate_clock_fu_90_clk_second_o_ap_vld;
    sc_signal< sc_lv<1> > clk_second;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_clk_second();
    void thread_leds();
    void thread_Advios_ssdm_threa_load_fu_108_p1();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_grp_Advios_LedControl_fu_70_clk_second();
    void thread_grp_Advios_modulate_clock_fu_90_clk_second_i();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
