# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab4/zybo_audio_constraints.xdc

# Block Designs: bd/design_4/design_4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4 || ORIG_REF_NAME==design_4} -quiet] -quiet

# IP: bd/design_4/ip/design_4_processing_system7_0_0/design_4_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_processing_system7_0_0 || ORIG_REF_NAME==design_4_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_zybo_audio_ctrl_0_0/design_4_zybo_audio_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_zybo_audio_ctrl_0_0 || ORIG_REF_NAME==design_4_zybo_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_0_0/design_4_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_0_0 || ORIG_REF_NAME==design_4_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_0_1/design_4_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_0_1 || ORIG_REF_NAME==design_4_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_0_2/design_4_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_0_2 || ORIG_REF_NAME==design_4_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ps7_0_axi_periph_0/design_4_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_4_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_rst_ps7_0_100M_0/design_4_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_4_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xbar_0/design_4_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xbar_0 || ORIG_REF_NAME==design_4_xbar_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_0_3/design_4_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_0_3 || ORIG_REF_NAME==design_4_axi_gpio_0_3} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_0/design_4_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_0 || ORIG_REF_NAME==design_4_auto_pc_0} -quiet] -quiet

# XDC: bd/design_4/design_4_ooc.xdc
