// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XAPPLY_H
#define XAPPLY_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xapply_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Fir_io_BaseAddress;
} XApply_Config;
#endif

typedef struct {
    u32 Fir_io_BaseAddress;
    u32 IsReady;
} XApply;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XApply_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XApply_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XApply_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XApply_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XApply_Initialize(XApply *InstancePtr, u16 DeviceId);
XApply_Config* XApply_LookupConfig(u16 DeviceId);
int XApply_CfgInitialize(XApply *InstancePtr, XApply_Config *ConfigPtr);
#else
int XApply_Initialize(XApply *InstancePtr, const char* InstanceName);
int XApply_Release(XApply *InstancePtr);
#endif

void XApply_Start(XApply *InstancePtr);
u32 XApply_IsDone(XApply *InstancePtr);
u32 XApply_IsIdle(XApply *InstancePtr);
u32 XApply_IsReady(XApply *InstancePtr);
void XApply_EnableAutoRestart(XApply *InstancePtr);
void XApply_DisableAutoRestart(XApply *InstancePtr);

u32 XApply_Get_Y(XApply *InstancePtr);
u32 XApply_Get_Y_vld(XApply *InstancePtr);
void XApply_Set_x(XApply *InstancePtr, u32 Data);
u32 XApply_Get_x(XApply *InstancePtr);

void XApply_InterruptGlobalEnable(XApply *InstancePtr);
void XApply_InterruptGlobalDisable(XApply *InstancePtr);
void XApply_InterruptEnable(XApply *InstancePtr, u32 Mask);
void XApply_InterruptDisable(XApply *InstancePtr, u32 Mask);
void XApply_InterruptClear(XApply *InstancePtr, u32 Mask);
u32 XApply_InterruptGetEnabled(XApply *InstancePtr);
u32 XApply_InterruptGetStatus(XApply *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
