// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xapply.h"

extern XApply_Config XApply_ConfigTable[];

XApply_Config *XApply_LookupConfig(u16 DeviceId) {
	XApply_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XAPPLY_NUM_INSTANCES; Index++) {
		if (XApply_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XApply_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XApply_Initialize(XApply *InstancePtr, u16 DeviceId) {
	XApply_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XApply_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XApply_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

